### ISSUE TITLE
OCD URLs are badly formatted

### ISSUE THREAD

**Issue by frankstrater** [openstate/npo-backstage-examples#2]
OCD URLs (_source.meta.ocd_url) are badly formatted. The following URL gives an error:

http://backstage-api.openstate.eu/v0/npo_journalistiek/journalistiek_Oben_290_89612

It seems it should be:

http://backstage-api.openstate.eu/v0/journalistiek/Oben_290_89612

Looks like meta.source_id 'npo_journalistiek' is the wrong name and that the URL doesn't use the correct object_id, which is 'Oben_290_89612'

Also, shouldn't the name be something like NPO URL instead of OCD URL...?

**Comment by siccovansas** [comment]
Thanks for notifying us. This issue has now been fixed! See the Changelog for details and other fixes: http://backstage-docs.openstate.eu/changes.html#changelog
